name: Deploy Next.js App to Server

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy and Rebuild on Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            git config --global --add safe.directory /var/www/octow_ru_usr/data/www/octow.ru
            cd /var/www/octow_ru_usr/data/www/octow.ru
            git pull origin master
            npm install
            npm run build
            pm2 restart octow || pm2 start npm --name "octow" -- run start
          EOF
